lab4/Controllers/DepositsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab4;
using lab4.ViewModels;
using System.Drawing.Printing;
using lab4.Infrastructure;
namespace lab4.Controllers
{
    public class DepositsController : Controller
    {
        private readonly BankDepositsContext _context;
        private readonly int pageSize = 10;

        public DepositsController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Deposits
        public IActionResult Index(int page = 1)
        {
            var depositView = HttpContext.Session.Get<DepositViewModel>("Deposit");
            if (depositView == null)
            {
                depositView = new DepositViewModel();
            }

            IQueryable<Deposit> depositsDbContext = _context.Deposits.Include(o => o.Currency);
            depositsDbContext = Search(depositsDbContext, depositView.Name, depositView.Term, depositView.Mindepositamount, depositView.CurrencyName, depositView.Rate, depositView.Additionalconditions);
            var count = depositsDbContext.Count();
            depositsDbContext = depositsDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            DepositViewModel deposits = new DepositViewModel
            {
                deposits = depositsDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                Name = depositView.Name,
                Term = depositView.Term,
                Mindepositamount = depositView.Mindepositamount,
                CurrencyName = depositView.CurrencyName,
                Rate = depositView.Rate,
                Additionalconditions = depositView.Additionalconditions
            };
            return View(deposits);
        }
        [HttpPost]
        public IActionResult Index(DepositViewModel depositView)
        {
            HttpContext.Session.Set("Deposit", depositView);

            return RedirectToAction("Index");  
        }
        // GET: Deposits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Deposits == null)
            {
                return NotFound();
            }

            var deposit = await _context.Deposits
                .Include(d => d.Currency)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deposit == null)
            {
                return NotFound();
            }

            return View(deposit);
        }

        // GET: Deposits/Create
        public IActionResult Create()
        {
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "Name");
            return View();
        }

        // POST: Deposits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Term,Mindepositamount,CurrencyId,Rate,Additionalconditions")] Deposit deposit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(deposit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "Name", deposit.CurrencyId);
            return View(deposit);
        }

        // GET: Deposits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Deposits == null)
            {
                return NotFound();
            }

            var deposit = await _context.Deposits.FindAsync(id);
            if (deposit == null)
            {
                return NotFound();
            }
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "Name", deposit.CurrencyId);
            return View(deposit);
        }

        // POST: Deposits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Term,Mindepositamount,CurrencyId,Rate,Additionalconditions")] Deposit deposit)
        {
            if (id != deposit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deposit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepositExists(deposit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CurrencyId"] = new SelectList(_context.Currencies, "Id", "Name", deposit.CurrencyId);
            return View(deposit);
        }

        // GET: Deposits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Deposits == null)
            {
                return NotFound();
            }

            var deposit = await _context.Deposits
                .Include(d => d.Currency)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deposit == null)
            {
                return NotFound();
            }

            return View(deposit);
        }

        // POST: Deposits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Deposits == null)
            {
                return Problem("Entity set 'BankDepositsContext.Deposits'  is null.");
            }
            var deposit = await _context.Deposits.FindAsync(id);
            if (deposit != null)
            {
                _context.Deposits.Remove(deposit);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepositExists(int id)
        {
          return (_context.Deposits?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private IQueryable<Deposit> Search(IQueryable<Deposit> deposits, string Name, double Term,
            decimal Mindepositamount, string CurrencyName, decimal Rate, string? Additionalconditions)
        {
            deposits = deposits.Where(o => (o.Name.Contains(Name ?? ""))
           && (o.Term == Term || Term == 0)
           && (o.Mindepositamount == Mindepositamount || Mindepositamount == 0)
           && (o.Currency.Name.Contains(CurrencyName ?? ""))
           && (o.Rate == Rate || Rate == 0)
           && (o.Additionalconditions.Contains(Additionalconditions ?? "")));

            return deposits;
        }
    }
}

lab4/Controllers/EmploeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab4;
using lab4.ViewModels;
using lab4.Infrastructure;

namespace lab4.Controllers
{
    public class EmploeesController : Controller
    {
        private readonly BankDepositsContext _context;
        private readonly int pageSize = 10;

        public EmploeesController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Emploees
        public IActionResult Index( int page = 1)
        {
            var emploeeView = HttpContext.Session.Get<EmploeeViewModel>("Emploee");
            if (emploeeView == null)
            {
                emploeeView = new EmploeeViewModel();
            }

            IQueryable<Emploee> emploeeDbContext = _context.Emploees;
            emploeeDbContext = Search(emploeeDbContext, emploeeView.Name, emploeeView.Surname, emploeeView.Middlename, emploeeView.Post, emploeeView.Dob);
            var count = emploeeDbContext.Count();
            emploeeDbContext = emploeeDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            EmploeeViewModel emploees = new EmploeeViewModel
            {
                emploees = emploeeDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                Name = emploeeView.Name,
                Surname = emploeeView.Surname,
                Middlename = emploeeView.Middlename,
                Post = emploeeView.Post,
                Dob = emploeeView.Dob   
            };
            return View(emploees);
        }

        [HttpPost]
        public IActionResult Index(EmploeeViewModel emploeeView)
        {
            HttpContext.Session.Set("Emploee", emploeeView);

            return RedirectToAction("Index");
        }

        // GET: Emploees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Emploees == null)
            {
                return NotFound();
            }

            var emploee = await _context.Emploees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emploee == null)
            {
                return NotFound();
            }

            return View(emploee);
        }

        // GET: Emploees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Emploees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Middlename,Post,Dob")] Emploee emploee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(emploee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(emploee);
        }

        // GET: Emploees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Emploees == null)
            {
                return NotFound();
            }

            var emploee = await _context.Emploees.FindAsync(id);
            if (emploee == null)
            {
                return NotFound();
            }
            return View(emploee);
        }

        // POST: Emploees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Middlename,Post,Dob")] Emploee emploee)
        {
            if (id != emploee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(emploee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmploeeExists(emploee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(emploee);
        }

        // GET: Emploees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Emploees == null)
            {
                return NotFound();
            }

            var emploee = await _context.Emploees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (emploee == null)
            {
                return NotFound();
            }

            return View(emploee);
        }

        // POST: Emploees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Emploees == null)
            {
                return Problem("Entity set 'BankDeposits1Context.Emploees'  is null.");
            }
            var emploee = await _context.Emploees.FindAsync(id);
            if (emploee != null)
            {
                _context.Emploees.Remove(emploee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmploeeExists(int id)
        {
          return (_context.Emploees?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private IQueryable<Emploee> Search(IQueryable<Emploee> emploees, string Name, string Surname, string Middlename, string Post, DateTime Dob)
        {
            emploees = emploees.Where(o => o.Name.Contains(Name ?? "")
            && (o.Surname.Contains(Surname ?? ""))
            && (o.Middlename.Contains(Middlename ?? ""))
            && (o.Post.Contains(Post ?? ""))
            && (o.Dob.Date == Dob || Dob == new DateTime() || Dob == null)    );

            return emploees;
        }
    }
}

lab4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab4</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab4.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emploees" asp-action="Index">Emploees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Investors" asp-action="Index">Investors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Operations" asp-action="Index">Operations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Deposits" asp-action="Index">Deposits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Currencies" asp-action="Index">Currencies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exchangerates" asp-action="Index">Exchangerates</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted"> 
        <div class="container">
            &copy; 2023 - lab4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>