lab4/ViewModels/OperationViewModel.cs
namespace lab4.ViewModels
{
    public class OperationViewModel
    {
        public IEnumerable<Operation> operations { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public string InvestorsName { get; set; }

        public DateTime Depositdate { get; set; }

        public DateTime Returndate { get; set; }

        public string Deposit { get; set; }

        public decimal Depositamount { get; set; }

        public decimal Refundamount { get; set; }

        public bool Returnstamp { get; set; }

        public string EmploeeName { get; set; }
    }
}

lab4/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab4;
using lab4.ViewModels;
using lab4.Infrastructure;

namespace lab4.Controllers
{
    public class OperationsController : Controller
    {
        private readonly BankDepositsContext _context;
        private readonly int pageSize = 10;   // количество элементов на странице

        public OperationsController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Operations
        
        public  IActionResult Index( int page = 1)
        {
            var operationView = HttpContext.Session.Get<OperationViewModel>("Operation");
            if (operationView == null)
            {
                operationView =new OperationViewModel();
            }

            IQueryable<Operation> operationsDbContext = _context.Operations.Include(o => o.Investors).Include(o => o.Emploee).Include(o => o.Deposit);
            operationsDbContext = Search(operationsDbContext, operationView.InvestorsName, operationView.Depositdate, operationView.Returndate, operationView.Deposit
    , operationView.Depositamount, operationView.Refundamount, operationView.Returnstamp, operationView.EmploeeName);
            var count = operationsDbContext.Count();
            operationsDbContext = operationsDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            OperationViewModel operations = new OperationViewModel
            {
                operations = operationsDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                InvestorsName = operationView.InvestorsName,
                Depositdate = operationView.Depositdate,
                Returndate = operationView.Returndate,
                Deposit = operationView.Deposit,
                Depositamount = operationView.Depositamount,
                Refundamount = operationView.Refundamount,
                Returnstamp = operationView.Returnstamp,
                EmploeeName = operationView.EmploeeName
            };
            return View(operations);
        }

        [HttpPost]
        public IActionResult Index(OperationViewModel operationView)
        {
            HttpContext.Session.Set("Operation", operationView);

            return RedirectToAction("Index");
        }

        // GET: Operations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Operations == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations
                .Include(o => o.Deposit)
                .Include(o => o.Emploee)
                .Include(o => o.Investors)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (operation == null)
            {
                return NotFound();
            }

            return View(operation);
        }

        // GET: Operations/Create
        public IActionResult Create()
        {
            ViewData["DepositId"] = new SelectList(_context.Deposits, "Id", "Name");
            ViewData["EmploeeId"] = new SelectList(_context.Emploees, "Id", "Id");
            ViewData["InvestorId"] = new SelectList(_context.Investors, "Id", "Id");
            return View();
        }

        // POST: Operations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Investorsid,Depositdate,Returndate,Depositid,Depositamount,Refundamount,Returnstamp,Emploeeid")] Operation operation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(operation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepositId"] = new SelectList(_context.Deposits, "Id", "Name", operation.DepositId);
            ViewData["EmploeeId"] = new SelectList(_context.Emploees, "Id", "Id", operation.EmploeeId);
            ViewData["InvestorId"] = new SelectList(_context.Investors, "Id", "Id", operation.InvestorId);
            return View(operation);
        }

        // GET: Operations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Operations == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations.FindAsync(id);
            if (operation == null)
            {
                return NotFound();
            }
            ViewData["DepositId"] = new SelectList(_context.Deposits, "Id", "Name", operation.DepositId);
            ViewData["EmploeeId"] = new SelectList(_context.Emploees, "Id", "Id", operation.EmploeeId);
            ViewData["InvestorId"] = new SelectList(_context.Investors, "Id", "Id", operation.InvestorId);
            return View(operation);
        }

        // POST: Operations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,InvestorId,Depositdate,Returndate,DepositId,Depositamount,Refundamount,Returnstamp,EmploeeId")] Operation operation)
        {
            if (id != operation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(operation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OperationExists(operation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepositId"] = new SelectList(_context.Deposits, "Id", "Name", operation.DepositId);
            ViewData["EmploeeId"] = new SelectList(_context.Emploees, "Id", "Id", operation.EmploeeId);
            ViewData["InvestorId"] = new SelectList(_context.Investors, "Id", "Id", operation.InvestorId);
            return View(operation);
        }

        // GET: Operations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Operations == null)
            {
                return NotFound();
            }

            var operation = await _context.Operations
                .Include(o => o.Deposit)
                .Include(o => o.Emploee)
                .Include(o => o.Investors)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (operation == null)
            {
                return NotFound();
            }

            return View(operation);
        }

        // POST: Operations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Operations == null)
            {
                return Problem("Entity set 'BankDeposits1Context.Operations'  is null.");
            }
            var operation = await _context.Operations.FindAsync(id);
            if (operation != null)
            {
                _context.Operations.Remove(operation);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OperationExists(int id)
        {
          return (_context.Operations?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private IQueryable<Operation> Search(IQueryable<Operation> operations, string InvestorsName,  DateTime Depositdate,
            DateTime Returndate, string Deposit, decimal Depositamount, decimal Refundamount,
            bool Returnstamp, string EmploeeName)
        {
             operations = operations.Where(o => o.Investors.Name.Contains(InvestorsName ?? "")
            && (o.Depositdate == Depositdate || Depositdate == new DateTime())
            && (o.Returndate == Returndate || Returndate == new DateTime())
            && (o.Deposit.Name.Contains(Deposit ?? ""))
            && (o.Depositamount == Depositamount || Depositamount ==0)
            && (o.Refundamount == Refundamount || Refundamount == 0)
            && (o.Returnstamp == Returnstamp)
            && (o.Emploee.Name.Contains(EmploeeName ?? "")));

            return operations;
        }
    }
}

lab4/Views/Operations/Create.cshtml
@model lab4.Operation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Operation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InvestorId" class="control-label"></label>
                <select asp-for="InvestorId" class ="form-control" asp-items="ViewBag.InvestorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Depositdate" class="control-label"></label>
                <input asp-for="Depositdate" class="form-control" />
                <span asp-validation-for="Depositdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Returndate" class="control-label"></label>
                <input asp-for="Returndate" class="form-control" />
                <span asp-validation-for="Returndate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepositId" class="control-label"></label>
                <select asp-for="DepositId" class ="form-control" asp-items="ViewBag.DepositId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Depositamount" class="control-label"></label>
                <input asp-for="Depositamount" class="form-control" />
                <span asp-validation-for="Depositamount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Refundamount" class="control-label"></label>
                <input asp-for="Refundamount" class="form-control" />
                <span asp-validation-for="Refundamount" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Returnstamp" /> @Html.DisplayNameFor(model => model.Returnstamp)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="EmploeeId" class="control-label"></label>
                <select asp-for="EmploeeId" class="form-control" asp-items="ViewBag.EmploeeId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab4/Views/Operations/Delete.cshtml
@model lab4.Operation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Operation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depositdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depositdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Returndate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Returndate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depositamount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depositamount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Refundamount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Refundamount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Returnstamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Returnstamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deposit.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emploee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emploee.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Investors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Investors.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

lab4/Views/Operations/Details.cshtml
@model lab4.Operation

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Operation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depositdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depositdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Returndate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Returndate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depositamount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depositamount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Refundamount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Refundamount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Returnstamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Returnstamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deposit.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emploee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emploee.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Investors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Investors.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

lab4/Views/Operations/Edit.cshtml
@model lab4.Operation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Operation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InvestorId" class="control-label"></label>
                <select asp-for="InvestorId" class="form-control" asp-items="ViewBag.InvestorId"></select>
                <span asp-validation-for="InvestorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Depositdate" class="control-label"></label>
                <input asp-for="Depositdate" class="form-control" />
                <span asp-validation-for="Depositdate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Returndate" class="control-label"></label>
                <input asp-for="Returndate" class="form-control" />
                <span asp-validation-for="Returndate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepositId" class="control-label"></label>
                <select asp-for="DepositId" class="form-control" asp-items="ViewBag.DepositId"></select>
                <span asp-validation-for="DepositId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Depositamount" class="control-label"></label>
                <input asp-for="Depositamount" class="form-control" />
                <span asp-validation-for="Depositamount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Refundamount" class="control-label"></label>
                <input asp-for="Refundamount" class="form-control" />
                <span asp-validation-for="Refundamount" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Returnstamp" /> @Html.DisplayNameFor(model => model.Returnstamp)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="EmploeeId" class="control-label"></label>
                <select asp-for="EmploeeId" class="form-control" asp-items="ViewBag.EmploeeId"></select>
                <span asp-validation-for="EmploeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab4/Views/Operations/Index.cshtml
@model lab4.ViewModels.OperationViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="badge rounded-pill bg-secondary">Create New</a>
</p>
<form action="@Url.Action("Index","Operations")" method="post">
    Дата:<input asp-for="@Model.Depositdate" name="Depositdate" type="date"></input>
    Дата возврата:<input asp-for="@Model.Returndate" name="Returndate" type="date"></input>
    Кол-во:@Html.TextBox("Depositamount", Model.Depositamount, new {type ="number", step = 0.01 })
    Кол-во возврата:@Html.TextBox("Refundamount", Model.Refundamount, new {type ="number", step = 0.01 })
    Печать:@Html.TextBox("Returnstamp", Model.Returnstamp, new {type ="checkbox" })
    Имя депозита:@Html.TextBox("Deposit", Model.Deposit)
    Имя работника:@Html.TextBox("EmploeeName", Model.EmploeeName)
    Имя инвестора:@Html.TextBox("InvestorsName", Model.InvestorsName)
    <input type="submit" value="Найти"></input>
</form>
<table class="table">
    <thead>
        <tr class="table-dark">
            <th>
                @Html.DisplayNameFor(model => model.Depositdate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Returndate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Depositamount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Refundamount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Returnstamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deposit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmploeeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvestorsName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.operations) {
        <tr class="table-secondary">
            <td>
                @Html.DisplayFor(modelItem => item.Depositdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Returndate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Depositamount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Refundamount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Returnstamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deposit.Name)
            </td>
            <td>
                    @{
                        var fullName = (item.Emploee != null) ? $"{item.Emploee.Surname} {item.Emploee.Name} {item.Emploee.Middlename}" : "N/A";
                    }

                    @Html.DisplayFor(modelItem => fullName)
            </td>
                <td>
                    @{
                        var fullName1 = (item.Investors != null) ? $"{item.Investors.Surname} {item.Investors.Name} {item.Investors.Middlename}" : "N/A";
                    }

                    @Html.DisplayFor(modelItem => fullName1)
                </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="badge bg-primary">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="badge bg-primary">Details</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="badge bg-primary">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<page-link page-model="@Model.PageViewModel" page-action="Index"></page-link>