lab4/ViewModels/InvestorViewModel.cs
namespace lab4.ViewModels
{
    public class InvestorViewModel
    {
        
        

        public IEnumerable<Investor> investors { get; set; }
        public PageViewModel PageViewModel { get; set; }

        public string Name { get; set; } 

        public string Surname { get; set; }

        public string Middlename { get; set; }

        public string Address { get; set; } 

        public string Phonenumber { get; set; } 

        public string PassportId { get; set; } 


    }


}

lab4/Controllers/InvestorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lab4;
using lab4.ViewModels;
using lab4.Infrastructure;

namespace lab4.Controllers
{
    public class InvestorsController : Controller
    {
        private readonly BankDepositsContext _context;
        private readonly int pageSize = 10;

        public InvestorsController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Investors
        
        public IActionResult Index( int page = 1)
        {
            var investorView = HttpContext.Session.Get<InvestorViewModel>("Investor");
            if (investorView == null)
            {
                investorView = new InvestorViewModel();
            }

            IQueryable<Investor> investorDbContext = _context.Investors;
            investorDbContext = Search(investorDbContext, investorView.Name, investorView.Surname, investorView.Middlename, investorView.Address, investorView.Phonenumber, investorView.PassportId);
            var count = investorDbContext.Count();
            investorDbContext = investorDbContext.Skip((page - 1) * pageSize).Take(pageSize);
            InvestorViewModel emploees = new InvestorViewModel
            {
                investors = investorDbContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                Name = investorView.Name,
                Surname = investorView.Surname,
                Middlename = investorView.Middlename,
                Address = investorView.Address,
                Phonenumber = investorView.Phonenumber,
                PassportId = investorView.PassportId
            };
            return View(emploees);
        }

        [HttpPost]
        public IActionResult Index(InvestorViewModel investorView)
        {
            HttpContext.Session.Set("Investor", investorView);

            return RedirectToAction("Index");
        }

        // GET: Investors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Investors == null)
            {
                return NotFound();
            }

            var investor = await _context.Investors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (investor == null)
            {
                return NotFound();
            }

            return View(investor);
        }

        // GET: Investors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Investors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Middlename,Address,Phonenumber,PassportId")] Investor investor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(investor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(investor);
        }

        // GET: Investors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Investors == null)
            {
                return NotFound();
            }

            var investor = await _context.Investors.FindAsync(id);
            if (investor == null)
            {
                return NotFound();
            }
            return View(investor);
        }

        // POST: Investors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Middlename,Address,Phonenumber,PassportId")] Investor investor)
        {
            if (id != investor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(investor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvestorExists(investor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(investor);
        }

        // GET: Investors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Investors == null)
            {
                return NotFound();
            }

            var investor = await _context.Investors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (investor == null)
            {
                return NotFound();
            }

            return View(investor);
        }

        // POST: Investors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Investors == null)
            {
                return Problem("Entity set 'BankDeposits1Context.Investors'  is null.");
            }
            var investor = await _context.Investors.FindAsync(id);
            if (investor != null)
            {
                _context.Investors.Remove(investor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvestorExists(int id)
        {
          return (_context.Investors?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private IQueryable<Investor> Search(IQueryable<Investor> investors, string Name, string Surname, string Middlename, string Address, string Phonenumber, string PassportId )
        {
            investors = investors.Where(o => o.Name.Contains(Name ?? "")
            && (o.Surname.Contains(Surname ?? ""))
            && (o.Middlename.Contains(Middlename ?? ""))
            && (o.Address.Contains(Address ?? ""))
            && (o.Phonenumber.Contains(Phonenumber ?? ""))
            && (o.PassportId.Contains(PassportId ?? "")));

            return investors;
        }
    }
}

lab4/Views/Investors/Create.cshtml
@model lab4.Investor

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Investor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Middlename" class="control-label"></label>
                <input asp-for="Middlename" class="form-control" />
                <span asp-validation-for="Middlename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phonenumber" class="control-label"></label>
                <input asp-for="Phonenumber" class="form-control" />
                <span asp-validation-for="Phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportId" class="control-label"></label>
                <input asp-for="PassportId" class="form-control" />
                <span asp-validation-for="PassportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab4/Views/Investors/Delete.cshtml
@model lab4.Investor

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Investor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Middlename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Middlename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassportId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassportId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

lab4/Views/Investors/Details.cshtml
@model lab4.Investor

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Investor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Middlename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Middlename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassportId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassportId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

lab4/Views/Investors/Edit.cshtml
@model lab4.Investor

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Investor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Middlename" class="control-label"></label>
                <input asp-for="Middlename" class="form-control" />
                <span asp-validation-for="Middlename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phonenumber" class="control-label"></label>
                <input asp-for="Phonenumber" class="form-control" />
                <span asp-validation-for="Phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PassportId" class="control-label"></label>
                <input asp-for="PassportId" class="form-control" />
                <span asp-validation-for="PassportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lab4/Views/Investors/Index.cshtml
@model lab4.ViewModels.InvestorViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="badge rounded-pill bg-secondary">Create New</a>
</p>
<form action="@Url.Action("Index","Investors")" method="post">
    Имя:@Html.TextBox("Name", Model.Name)
    Фамилия:@Html.TextBox("Surname", Model.Surname)
    Отчество:@Html.TextBox("Middlename", Model.Middlename)
    Адресс:@Html.TextBox("Address", Model.Address)
    Номер телефона:@Html.TextBox("Phonenumber", Model.Phonenumber)
    Пасорт:@Html.TextBox("PassportId", Model.PassportId)
    <input type="submit" value="Найти"></input>
</form>
<table class="table">
    <thead>
        <tr class="table-dark">
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Middlename)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PassportId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.investors) {
        <tr class="table-secondary">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Middlename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phonenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PassportId)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="badge bg-primary">Edit</a> 
                    <a asp-action="Details" asp-route-id="@item.Id" class="badge bg-primary">Details</a> 
                    <a asp-action="Delete" asp-route-id="@item.Id" class="badge bg-primary">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<page-link page-model="@Model.PageViewModel" page-action="Index"></page-link>